services:

  db:
    image: mysql:8
    container_name: ingsof_db
    environment:
      MYSQL_DATABASE: ingsof
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3310:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./backend
    container_name: proyectoCRF_backend
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
    ports:
      - "8082:8080"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: proyectoCRF_frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: always